const projectsData = [
  {
    id: "1",
    path: "threejs",
    img: "src/img/threejs_thumbnail.png",
    name: "3Rayan",
    category: "web",
    tags: ["3D", "Web development"],
    shortdescription: "3D-name made in ThreeJS",
  },
  {
    id: "2",
    path: "chatrix",
    img: "src/img/chatrix.png",
    name: "Chatrix",
    category: "web",
    tags: ["Web development", "UI Design"],
    shortdescription: "A live chat app made to test web sockets",
  },
  {
    id: "3",
    path: "quizapp",
    img: "src/img/quizapp.png",
    name: "Ask & Learn",
    category: "web",
    tags: ["Web development", "UI Design"],
    shortdescription: "A quiz app to play with your friends",
  },
  {
    id: "4",
    path: "festirap",
    img: "src/img/festirap.png",
    name: "festirap.",
    category: "design",
    tags: ["UI/UX Design", "Branding"],
    shortdescription: "A fictif rap festival for the youth of Brussels",
  },
  {
    id: "5",
    path: "steamredesign",
    img: "src/img/steam_thumbnail.png",
    name: "Steam redesign",
    category: "web",
    tags: ["UI/UX Design", "Web development"],
    shortdescription:
      "A redesign of the most famous video game distribution service",
  },
  {
    id: "6",
    path: "finalshow",
    img: "src/img/finalshow.png",
    name: "Final Show",
    category: "other",
    tags: ["Storytelling", "Script"],
    shortdescription:
      "A show hosted by the students of Multimedia & Creative Technologies",
  },
  {
    id: "7",
    path: "omega",
    img: "src/img/omega_thumbnail.png",
    name: "OMEGA",
    category: "web",
    tags: ["UI/UX Design", "Web Development"],
    shortdescription: "A modern and performing gaming search engine",
  },
  {
    id: "8",
    path: "learnify",
    img: "src/img/learnify_thumbnail.png",
    name: "Learnify",
    category: "web",
    tags: ["UI/UX Design", "Web Development"],
    shortdescription: "A new way to make online lessons less boring",
  },
  {
    id: "9",
    path: "funkymood",
    img: "src/img/funkymood_thumbnail.png",
    name: "Funky mood",
    category: "design",
    tags: ["Branding", "Concept"],
    shortdescription: "Innovating the art of gifting mixtapes",
  },
  {
    id: "10",
    path: "kunstinhuis",
    img: "src/img/kunstinhuis_thumbnail.png",
    name: "Kunst In Huis",
    category: "design",
    tags: ["Branding", "UI/UX Design", "Prototyping"],
    shortdescription: "Rebranding of Kunst In Huis",
  },
  // Add more projects with similar structure as above
];
export default projectsData;
